### ISSUE TITLE
off-by-one error in indel vcf representation of mummer output

### ISSUE THREAD

**Issue by 0xaf1f** [MatteoSchiavinato/all2vcf#4]
My labmate had written a [simple script](https://gitlab.com/LPCDRP/utils/-/blob/master/mummer-extras/src/mummer-snps2vcf) to do the mummer snps to vcf conversion many years ago. I had early this year switched to using your tool since it produced a better vcf header, but we ended up really suffering from the indel representation bug #2.

I see, however, that it isn't totally fixed. First, the mummer documentation describes the format in case of indels:

> The descriptions for each header tag follows. [P1] position of the SNP in the reference sequence. For indels, this position refers to the 1-based position of the first character before the indel, e.g. for an indel at the very beginning of a sequence this would report 0. For indels on the reverse strand, this position refers to the forward-strand position of the first character before indel on the reverse-strand, e.g. for an indel at the very end of a reverse complemented sequence this would report 1.

https://mummer.sourceforge.net/manual/#snps

Consider this test case:

```
$ cat seq1.fasta
>EMBOSS_001
gacgaatattgaggagatagactttaccaaaccccaccgggtagcagggctccgtgccaa
attgatccccgtggagccacgaagtctctacggtggaacg
```

Copy it, plant an insertion of a T after the 4th base, and call it seq2.fasta:
```
$ cat seq2.fasta
>EMBOSS_001_ins
gacgtaatattgaggagatagactttaccaaaccccaccgggtagcagggctccgtgccaa
attgatccccgtggagccacgaagtctctacggtggaacg
```

Run `dnadiff` and examine the snps file:
```
$ dnadiff seq1.fasta seq2.fasta 
Building alignments
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "out.ntref" of length 101
# construct suffix tree for sequence of length 101
# (maximum reference length is 2305843009213693948)
# (maximum query length is 18446744073709551615)
# CONSTRUCTIONTIME /path/to/mummer-3.23/mummer out.ntref 0.00
# reading input file "/tmp/tmp.RtxIrqEzJr/seq2.fasta" of length 101
# matching query-file "/tmp/tmp.RtxIrqEzJr/seq2.fasta"
# against subject-file "out.ntref"
# COMPLETETIME /path/to/mummer-3.23/mummer out.ntref 0.00
# SPACE /path/to/mummer-3.23/mummer out.ntref 0.00
4: FINISHING DATA
Filtering alignments
Extracting alignment coordinates
Analyzing SNPs
Extracting alignment breakpoints
Generating report file
```

```
$ cat out.snps 
4       .       T       5       4       4       100     101     1       1       EMBOSS_001      EMBOSS_001_ins
``` 

Since we planted this indel after the 4th base, we know for a fact that the VCF representation for POS/REF/ALT should be
```
4    G    GT
```

Now `all2vcf` latest master (a couple commits after 0.7.4):
```
$ all2vcf/all2vcf mummer --snps out.snps --reference seq1.fasta
EMBOSS_001      3       .       c       cT      .       .       INDEL   EMBOSS_001:4
```

So the position of the insertion is wrong and represents a different variant altogether.

**Comment by MatteoSchiavinato** [comment]
Hi, 

Thanks for using my tool. I am afraid, however, that the error is not on my side. In the VCF documentation (which is the output format of all2vcf mummer) there is a clear explanation of how indels should be represented. See chapter 5.2.2 of the official documentation here:
https://samtools.github.io/hts-specs/VCFv4.2.pdf

The representation of an indel in a VCF file is 0-based (not 1-based as mummer) and begins with the character that precedes the indel (in your example, a "c"). 

Hence, what all2vcf mummer is doing is actually right, because it's converting from Mummer snps format to VCF. 

What it should also do, however, and it wasn't doing so far, is to capitalize the characters in the sequence when representing them. Here, in your example, it takes a "c" because it's the character that precedes the indel, but it doesn't capitalize it. I never worked with lowercase sequences, since they are usually used to represent masked regions, but that's worth correcting. 

I'm closing this issue for now, and I hope that my explanation was clear enough!

**Comment by 0xaf1f** [comment]
The specification says the position is 1-based. Even in the section you are referring to. You might see it as 0-based because the position is the locus immediately before the insertion, but that is the 1-based position of the preceding reference allele.

And section 1.4.1 explicitly says so
> 2. POS - position: The reference position, with the 1st base having position 1. 

The insertion in my example is after the 4th base (G). Your tool is incorrectly reporting it as after the third base (C).

**Comment by MatteoSchiavinato** [comment]
In the example at paragraph 5.2.2, they introduce an insertion of the bases "TAG" after a cytosine. The cytosine (C) in question is in position 3 if you start counting from 1 (see table in 5.2.2). 

In the same paragraph, they show how the VCF file would look like. Note that the VCF line marks position 3 for the insertion, although that's actually the **last position before the insertion**, as per specification. 

EDIT: 
When I said "0-based" in a previous comment, I was misled by the fact that the position annotated in a VCF insertion is in fact the last one _before_  the insertion. This and the 0-based first indel position are the same number, so I got confused, also because I worked on this module years ago and I didn't have the situation fresh in my mind. Nevertheless, what I wrote in this comment is the final answer and I am sure that the output is correct, since it has to represent the last position before the insertion (as per the 5.2.2 example).

**Comment by 0xaf1f** [comment]
My friend, the table is backing up what I'm saying.

> In the example at paragraph 5.2.2, they introduce an insertion of the bases "TAG" after a cytosine. The cytosine (C) in question is in position 3 if you start counting from 1 (see table in 5.2.2).

Your words are correct but not what your tool is doing. This is the VCF record they show for the example.

```
#CHROM    POS ID REF   ALT   QUAL    FILTER   INFO
20        3   .  C     CTAG  .       PASS     DP=100
``` 

```
a t C - - - g a
a t C T A G g a
```

Now...look at the example I've been trying to get your attention on and spent a good amount of time to demonstrate the bug to you.

My example was

```
g a c g - a a
g a c g t a a 
```

I am trying to tell you that correct output (consistent with the specification) is 

```
4    G    GT
```

and all2vcf is incorrectly giving

```
3    C    CT
```

**Comment by MatteoSchiavinato** [comment]
I see what you mean. May I ask you your nucmer/mummer package version? 

I went through my very old notes (ca. 2016) and I justified the -1 in the position writing that nucmer show-snps -T was representing indels by reporting the first indel position in 1-based format. Now, I tried with nucmer 3.1 and the problem you mention appears. 

I have done a quick search (I'm on holiday) but I haven't found whether this was changed over the years. As you may have noticed I have never published this tool in a paper so it's not something I actively maintain, therefore cross-version issues could happen sometimes - although I don't know if this is the case. 

I am going to commit a new version soon (5 mins) that fixes this issue. 

One last thing though: I haven't particularly appreciated how I have been approached to fix this. Maybe it wasn't your intention, but I think there are better ways to point out a bug, especially if we seem not to understand each other. If I got that wrong too, well, sorry.

**Comment by 0xaf1f** [comment]
> May I ask you your nucmer/mummer package version?

My nucmer is v3.1 and mummer suite as a whole is v3.23. That was [last released in 2011](https://sourceforge.net/projects/mummer/files/mummer/). There is a mummer 4 out now as a separate project on github, but I haven't switched to using it either.

> I haven't particularly appreciated how I have been approached to fix this. Maybe it wasn't your intention

It definitely wasn't my intention. I was a bit exasperated in writing my previous message because I felt that I was being shut out, but in my earlier messages, I was definitely just trying to be direct and methodical. I spent the time to make a test dataset and demonstrate the problem in an easily reproducible way and had the issue immediately closed on me. I'm sorry for how it came across.

Many thanks for your attention, especially while on holiday. It is a severe bug that I hope affected users will be able to notice soon.

**Comment by 0xaf1f** [comment]
(just adding some related links here)
patch targeting the issue: https://github.com/MatteoSchiavinato/all2vcf/commit/e50a3e8cdc2d6181c88d1bd4f592c5326ba1d285 
release [0.7.8](https://github.com/MatteoSchiavinato/all2vcf/releases/tag/v0.7.8) includes the patch
